# Directory containing incoming folder, where to store logs, etc. Relative to
# the config file directory.
root: /var/www/keter
# Keter can listen on multiple ports for incoming connections. These ports can
# have HTTPS either enabled or disabled.
listeners:
    # HTTP
    - host: "*4" # Listen on all IPv4 hosts
      port: 80 # Could be used to modify port
    # HTTPS
#    - host: "*4"
#      #port: 443
#      key: key.pem
#      certificate: certificate.pem

# User to run applications as
setuid: www-data

# Get the user's IP address from x-forwarded-for. Useful when sitting behind a
# load balancer like Amazon ELB.
# ip-from-header: true